
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog, Label
from PIL import Image, ImageTk

import ml

global filename
global img
global ph


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def UploadAction(event=None):
    global filename
    global img
    global ph
    filename = filedialog.askopenfilename()
    print('Selected:', filename)
    img = Image.open(filename)
    img = img.resize((480, 360), Image.ANTIALIAS)
    ph = ImageTk.PhotoImage(img, master=window)

def DisplayAction(event=None):
    canvas.create_image(550, 138, anchor="nw", image=ph)
    
def PredictAction(event=None):
    global filename
    prediction, top3 = ml.PredictImage(filename)
    print(prediction)
    print(top3)
    
    guess1['text'] = top3[0]
    guess2['text'] = top3[1]
    guess3['text'] = top3[2]
    
window = Tk()
window.title("City Guesser Ai")

window.geometry("1257x724")
window.configure(bg = "#002C3E")

canvas = Canvas(
    window,
    bg = "#002C3E",
    height = 724,
    width = 1257,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

# UPLOAD BUTTON
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=UploadAction,
    relief="flat"
)
button_1.place(
    x=33.0,
    y=131.0,
    width=232.0,
    height=135.0
)

# DISPLAY BUTTON
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=DisplayAction,
    relief="flat"
)
button_2.place(
    x=28.0,
    y=266.0,
    width=224.0,
    height=141.0
)

# PREDICT BUTTON
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command = lambda: PredictAction(filename),
    relief="flat"
)
button_3.place(
    x=39.0,
    y=407.0,
    width=226.0,
    height=158.0
)

# TITLE BAR
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=0.0,
    y=0.0,
    width=1257.0,
    height=74.0
)

canvas.create_rectangle(
    315.0,
    138.0,
    318.0,
    508.0,
    fill="#78BCC4",
    outline="")

canvas.create_text(
    503.0,
    526.0,
    anchor="nw",
    text="1.\n\n2.\n\n3.",
    fill="#F7F8F3",
    font=("OpenSansRoman SemiBold", 25 * -1))

# GUESS LABEL 1
guess1 = Label(window, anchor="nw", bg="#F7F8F3", font=("OpenSansRoman SemiBold", 25 * -1), fg="#78BCC4", text="~", pady=0, padx=50)
guess1.place(x=720.0, y=524.0)

# GUESS LABEL 2
guess2 = Label(window, anchor="c", bg="#F7F8F3", font=("OpenSansRoman SemiBold", 25 * -1), fg="#78BCC4", text="~", pady=0, padx=50)
guess2.place(x=720.0, y=582.0)

# GUESS LABEL 3
guess3 = Label(window, anchor="nw", bg="#F7F8F3", font=("OpenSansRoman SemiBold", 25 * -1), fg="#78BCC4", text="~", pady=0, padx=50)
guess3.place(x=720.0, y=645.0)

def round_rectangle(x1, y1, x2, y2, r=25, **kwargs):    
    points = (x1+r, y1, x1+r, y1, x2-r, y1, x2-r, y1, x2, y1, x2, y1+r, x2, y1+r, x2, y2-r, x2, y2-r, x2, y2, x2-r, y2, x2-r, y2, x1+r, y2, x1+r, y2, x1, y2, x1, y2-r, x1, y2-r, x1, y1+r, x1, y1+r, x1, y1)
    return canvas.create_polygon(points, **kwargs, smooth=True)

round_rectangle(548, 520, 1048, 560, fill="#F7F8F3")
round_rectangle(548, 580, 1048, 620, fill="#F7F8F3")
round_rectangle(548, 640, 1048, 680, fill="#F7F8F3")

window.resizable(False, False)
window.mainloop()
